language: node_js
node_js:
  - '8.10'
before_install:
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
  - node --version
  - npm --version
  - nvm --version
install:
  - npm ci
test:
  - npm t
script:
  - npm run zip
deploy:
  on:
    branch: master
  provider: lambda
  function_name: verifynpm-get-badge
  zip: "./compiled/bundle.zip"
  region: us-east-2
  role: arn:aws:iam::541605000355:role/lambda_code_deploy
  runtime: nodejs8.10
  handler_name: handler
  access_key_id: AKIAJIOMAZIG6DL7U76A
  secret_access_key:
    secure: ZWhxBLOoWdKENEnBezN2rKj4RqhVVrFjLUhypxLgynxbdKcEMq89X6Lfvyl++3bsrigA76YEF9pP3Ym8NA8J5PJod2kiKFSvuriMEn2u/vpSFs8f5NtY+N2yH8GeGSQzy1LVgQ70B2WMAAdCx7Esv3ln6eGMfMHAtEUMwSNEz8rMxivtjZvElSMzXfpNFwNZ1Vd2qVM3ODP0IwAHtbaKpnzI478PvZGM6wOe6s4BprXwZtu5QX1Wz18ToOcQmWreMaiBdHTbW6n7FR+aOaXOmTSN8DDVglFmmBwBJ6vlq7tgQe4s5gWCTFAKCdaqx/cr4L5NpNouVPPoL/zBUz4uJ5ckkHACN/tpObwCbXeENybofWktpCXTxrYEAF4i/EGtXaFAfhhgpuwb5Bqv/aF6wXy9UaV/njcbfoLU7d3JQeQUFVQYfe28xljDipa8hCHbgY9uDNpAwJmWgJnjgVmXCNFs+fkCmk8oduK5YejfTuW/EemIKRQWF07B0I5zkBVAwphIg0fRGWYyrfuhayV7Oiv+f1b2S0B2SAcUFDeoQnsPC3Srbag2HrksdIYwNGBVUalIT0yuTdSnXj3TzQAsgkpeIfxO7U5/kb6jwF94G+tOorBZLIGFyeTFZ6dSPWom6TqJH24I8Ws7WpnZ3j+sG9XXPeVtGvykKMt3MWWgMCY=
